default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  user: postgres
  password: postgres

development:
  <<: *default
  database: scrapper

test: &test
  <<: *default
  database: scrapper_test
